DbMetadata/Models/Metadata/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbMetadata.Models.Metadata
{
    public class Project
    {
        public int ProjectId { get; set; }

        public Department OwnerDepartment { get; set; }

        public string Name { get; set; }

        public List<ProjectProperty> Properties { get; set; }

        public Project()
        {

        }
    }
}

DbMetadata/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbMetadata.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace DbMetadata.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly MetadataContext _context;

        public DocumentsController(MetadataContext context)
        {
            _context = context;
        }

        // GET: Documents
        public async Task<IActionResult> Index()
        {
            return View(await _context.Documents.Include(m=>m.File).ToListAsync());
        }

        // GET: Documents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(m=>m.File)
                .Include(m=>m.File.PrevVersion)
                .SingleOrDefaultAsync(m => m.DocumentId == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _context.Projects
                .Include(o => o.Documents)
                .SingleOrDefaultAsync(m => m.ProjectId == id);

            //var document = new Document() { OwnerProject = project.Result };
            //project.Result.Documents.Add(document);
            return View(new DocumentViewModel() {ProjectId = project.Result.ProjectId });
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DocumentViewModel documentViewModel)
        {
            if (ModelState.IsValid)
            {
                var document = new Document();
                var project = _context.Projects.Include(p => p.Documents).FirstOrDefault(p=>p.ProjectId == documentViewModel.ProjectId);
                var file = new DocumentFile();
                file.Name = documentViewModel.Name;
                file.ModifiedTime = DateTime.Now;
                using (var memoryStream = new MemoryStream())
                {
                    await documentViewModel.Data.CopyToAsync(memoryStream);
                    file.Data = memoryStream.ToArray();
                }

                _context.Add(file);
                document.File = file;
                project.Documents.Add(document);
                _context.Add(document);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(documentViewModel);
        }

        // GET: Documents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.SingleOrDefaultAsync(m => m.DocumentId == id);
            if (document == null)
            {
                return NotFound();
            }
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DocumentId,Name,Data,ModifiedTime")] Document document)
        {
            if (id != document.DocumentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(document);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.DocumentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(document);
        }

        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(m=>m.File)
                .SingleOrDefaultAsync(m => m.DocumentId == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var document = await _context.Documents.Include(m=>m.File).SingleOrDefaultAsync(m => m.DocumentId == id);
            var file = await _context.DocumentFiles.Include(m => m.PrevVersion).SingleOrDefaultAsync(m => m.DocumentFileId == document.File.DocumentFileId);
            DocumentFile nextFile = null;
            do
            {
                if(file.PrevVersion != null)
                    nextFile = await _context.DocumentFiles.Include(m => m.PrevVersion).SingleOrDefaultAsync(m => m.DocumentFileId == file.PrevVersion.DocumentFileId);

                _context.DocumentFiles.Remove(file);
                if (nextFile == null)
                    break;
                else
                    file = nextFile;
            } while (true);
            _context.Documents.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(int id)
        {
            return _context.Documents.Any(e => e.DocumentId == id);
        }

        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var documentFile = await _context.DocumentFiles.SingleOrDefaultAsync(m => m.DocumentFileId == id);
            if (documentFile == null)
            {
                return NotFound();
            }
            return File(documentFile.Data, "application/x-msdownload", documentFile.Name);
        }
    }
}

DbMetadata/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbMetadata.Models;
using ClosedXML.Excel;
using System.IO;

namespace DbMetadata.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly MetadataContext _context;

        public ProjectsController(MetadataContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var project = await _context.Projects
                .Include(p=>p.OwnerDepartment)
                .Include(p=>p.Properties)
                .Include(p=>p.Documents)
                .Include(p=>p.Tasks)
                .Include(p=>p.Links)
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            foreach(var doc in project.Documents)
            {
                var temp = _context.Documents.Include(m=>m.File).SingleOrDefault(m => m.DocumentId == doc.DocumentId);
                doc.File = temp.File;
            }
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = _context.Departments
                .Include(d =>d.Projects)
                .SingleOrDefaultAsync(m => m.DepartmentId == id);

            var project = new Project() { OwnerDepartment = department.Result };
            department.Result.Projects.Add(project);
            //var property = new DepartmentProperty() { OwnerDepartment = department.Result };
            //organization.Result.Properties.Add(property);
            //_context.Attach(property);
            return View(project);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Project project)
        {
            if (ModelState.IsValid)
            {
                project.OwnerDepartment = _context.Departments.Find(project.OwnerDepartment.DepartmentId);
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,Name")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ProjectId == id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectId == id);
        }

        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(m => m.Properties)
                .Include(m => m.OwnerDepartment.Properties)
                .Include(m => m.OwnerDepartment.OwnerOrganization.Properties)
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            var document = new XLWorkbook(
                Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationBasePath +
                "..\\..\\..\\sample.xlsx");
            var ws = document.Worksheet(1);
            ws.Cell("A1").Value = project.OwnerDepartment.OwnerOrganization.Name;
            ws.Cell("A2").Value = project.OwnerDepartment.Name;
            ws.Cell("A3").Value = project.Name;

            MemoryStream stream = new MemoryStream();
            document.SaveAs(stream);
            stream.Position = 0;

            return File(stream, "application/x-msdownload", project.Name + "_project_card.xlsx");
            //FileStream fileStream = new FileStream(Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationBasePath +
            //    "..\\..\\..\\sample.xlsx", FileMode.Open, FileAccess.Read);
            //byte[] file = new byte[fileStream.Length];
            //fileStream.Read(file, 0, file.Length);
            //return File( file, "application/x-msdownload", project.Name + "_project_card.xlsx");
        }
        //    return File(documentFile.Data, "application/x-msdownload", documentFile.Name);
        //}


        // GET api/Projects/5/GanttData
        [HttpGet]
        [Route("api/Projects/{projectId}/GanttData")]
        public GanttDto GanttData(int projectId)
        {
            return new GanttDto
            {
                data = GetTask(projectId),
                links = GetLink(projectId)
            };
        }

        // GET api/Task
        public IEnumerable<TaskDto> GetTask(int projectId)
        {
            return _context.Tasks
                .Where(t=>t.ProjectId == projectId)
                .ToList()
                .Select(t => (TaskDto)t);
        }


        // GET api/Task/5
        [HttpGet]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public TaskDto GetTask(int projectId,int id)
        {
            return (TaskDto)_context
                .Tasks
                .Find(id);
        }

        // POST api/Task
        [HttpPost]
        [Route("api/Projects/{projectId}/Task")]
        public IActionResult CreateTask(int projectId,TaskDto taskDto)
        {
            var newTask = (DbMetadata.Models.Task)taskDto;

            //save id
            newTask.ProjectId = projectId;

            //save to project
            var project = _context.Projects
                .Include(p => p.Tasks)
                .SingleOrDefaultAsync(m => m.ProjectId == projectId);
            project.Result.Tasks.Add(newTask);

            _context.Tasks.Add(newTask);

            _context.SaveChanges();

            return Ok(new
            {
                tid = newTask.TaskId,
                action = "inserted"
            });
        }

        // DELETE api/Task/5
        [HttpDelete]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public IActionResult DeleteTask(int projectId,int id)
        {
            var task = _context.Tasks.Find(id);
            if (task != null)
            {
                _context.Tasks.Remove(task);
                _context.SaveChanges();
            }

            return Ok(new
            {
                action = "deleted"
            });
        }

        // PUT api/Task/5
        [HttpPut]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public IActionResult EditTask(int projectId, int id, TaskDto taskDto)
        {
            var updatedTask = (DbMetadata.Models.Task)taskDto;
            updatedTask.ProjectId = projectId;
            updatedTask.TaskId = id;
            _context.Entry(updatedTask).State = EntityState.Modified;
            _context.SaveChanges();

            return Ok(new
            {
                action = "updated"
            });
        }

DbMetadata/Views/Projects/Create.cshtml
@model DbMetadata.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerDepartment" class="control-label"></label>
                <input asp-for="OwnerDepartment.DepartmentId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbMetadata/Views/Projects/Delete.cshtml
@model DbMetadata.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DbMetadata/Views/Projects/Details.cshtml
@model DbMetadata.Models.Project

@{
    ViewData["Title"] = "Details";
}


<meta name="viewport" content="width=device-width" />
<title>Index</title>
<link href="https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.css"
      rel="stylesheet" type="text/css" />
<script src="https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.js"></script>
<script>

        document.addEventListener("DOMContentLoaded", function(event) {
            // specifying the date format
            gantt.config.xml_date = "%Y-%m-%d %H:%i";
            // initializing gantt
            gantt.init("gantt_here");

            // initiating data loading
            gantt.load("/api/Projects/@Model.ProjectId/GanttData");
            // initializing dataProcessor
            var dp = new gantt.dataProcessor("/api/Projects/@Model.ProjectId/");/*как-то так роутинг сделать*/
            // and attaching it to gantt
            dp.init(gantt);
            // setting the REST mode for dataProcessor
            dp.setTransactionMode("REST");
        });

</script>

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OwnerDepartment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OwnerDepartment.DepartmentId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>


<p>
    <a asp-controller="ProjectProperties" asp-action="Create" asp-route-id="@Model.ProjectId">Create New Property</a>
</p>
@{Html.RenderPartial("../ProjectProperties/Index", Model.Properties); }

@*<p>
    <a asp-controller="Tasks" asp-action="Create" asp-route-id="@Model.ProjectId">Create New Task</a>
</p>
@{Html.RenderPartial("../Tasks/Index", Model.Tasks); }*@
<div id="gantt_here" style="width: 100%; height: 100vh;"></div>

<p>
    <a asp-controller="Documents" asp-action="Create" asp-route-id="@Model.ProjectId">Create New Document</a>
</p>
@{Html.RenderPartial("../Documents/Index", Model.Documents); }

<div>
    <a asp-action="Download" asp-route-id="@Model.ProjectId">Download project card</a> |
    <a asp-action="Edit" asp-route-id="@Model.ProjectId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DbMetadata/Views/Projects/Edit.cshtml
@model DbMetadata.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbMetadata/Views/Projects/Index.cshtml
@model IEnumerable<DbMetadata.Models.Project>

@{
    ViewData["Title"] = "Index";
}

<h4>Projects</h4>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-controller="Projects" asp-action="Edit" asp-route-id="@item.ProjectId">Edit</a> |
                <a asp-controller="Projects" asp-action="Details" asp-route-id="@item.ProjectId">Details</a> |
                <a asp-controller="Projects" asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>