PDM/Models/OrganizationProperty.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PDM.Models
{
    public class OrganizationProperty : AbstractProperty
    {
        public int OrganizationPropertyId { get; set; }

        public Organization OwnerOrganization { get; set; }
    }
}

PDM/Controllers/OrganizationPropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PDM.Models;

namespace PDM.Controllers
{
    [Authorize]
    public class OrganizationPropertiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrganizationPropertiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrganizationProperties
        public  async Task<IActionResult> Index()
        {
            return View(await _context.OrganizationProperties.Include(p => p.OwnerOrganization).ToListAsync());
            //return RedirectToAction("Index", "Organizations");
        }

        // GET: OrganizationProperties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organizationProperty = await _context.OrganizationProperties
                .Include(p=>p.OwnerOrganization)
                .SingleOrDefaultAsync(m => m.OrganizationPropertyId == id);
            if (organizationProperty == null)
            {
                return NotFound();
            }

            return View(organizationProperty);
        }

        // GET: OrganizationProperties/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = _context.Organizations
                .Include(o => o.Properties)
                .SingleOrDefaultAsync(m => m.OrganizationId == id);

            var property = new OrganizationProperty() { OwnerOrganization = organization.Result };
            organization.Result.Properties.Add(property);
            _context.Attach(property);
            return View(property);
        }

        // POST: OrganizationProperties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrganizationProperty model)
        {
            if (ModelState.IsValid)
            {
                model.OwnerOrganization = _context.Organizations.Find(model.OwnerOrganization.OrganizationId);
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: OrganizationProperties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organizationProperty = await _context.OrganizationProperties.SingleOrDefaultAsync(m => m.OrganizationPropertyId == id);
            if (organizationProperty == null)
            {
                return NotFound();
            }
            return View(organizationProperty);
        }

        // POST: OrganizationProperties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrganizationPropertyId,Title,Value")] OrganizationProperty organizationProperty)
        {
            if (id != organizationProperty.OrganizationPropertyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organizationProperty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationPropertyExists(organizationProperty.OrganizationPropertyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(organizationProperty);
        }

        // GET: OrganizationProperties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organizationProperty = await _context.OrganizationProperties
                .SingleOrDefaultAsync(m => m.OrganizationPropertyId == id);
            if (organizationProperty == null)
            {
                return NotFound();
            }

            return View(organizationProperty);
        }

        // POST: OrganizationProperties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organizationProperty = await _context.OrganizationProperties.SingleOrDefaultAsync(m => m.OrganizationPropertyId == id);
            _context.OrganizationProperties.Remove(organizationProperty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationPropertyExists(int id)
        {
            return _context.OrganizationProperties.Any(e => e.OrganizationPropertyId == id);
        }
    }
}

PDM/Views/OrganizationProperties/Create.cshtml
@model PDM.Models.OrganizationProperty

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>OrganizationProperty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerOrganization" class="control-label"></label>
                <input asp-for="OwnerOrganization.OrganizationId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Organizations" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PDM/Views/OrganizationProperties/Delete.cshtml
@model PDM.Models.OrganizationProperty

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrganizationProperty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrganizationPropertyId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PDM/Views/OrganizationProperties/Details.cshtml
@model PDM.Models.OrganizationProperty

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>OrganizationProperty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganizationPropertyId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganizationPropertyId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OwnerOrganization)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OwnerOrganization.OrganizationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.OrganizationPropertyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PDM/Views/OrganizationProperties/Edit.cshtml
@model PDM.Models.OrganizationProperty

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>OrganizationProperty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrganizationPropertyId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PDM/Views/OrganizationProperties/Index.cshtml
@model IEnumerable<PDM.Models.OrganizationProperty>

@{
    ViewData["Title"] = "Index";
}

<h4>Organization Properties</h4>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OwnerOrganization)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Value)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerOrganization.OrganizationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                <a asp-controller="OrganizationProperties" asp-action="Edit" asp-route-id="@item.OrganizationPropertyId">Edit</a> |
                <a asp-controller="OrganizationProperties" asp-action="Details" asp-route-id="@item.OrganizationPropertyId">Details</a> |
                <a asp-controller="OrganizationProperties" asp-action="Delete" asp-route-id="@item.OrganizationPropertyId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>