DbMetadata/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbMetadata.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }

        public string Name { get; set; }

        public Organization OwnerOrganization { get; set; }

        public ICollection<DepartmentProperty> Properties { get; set; }

        public ICollection<Project> Projects { get; set; }
    }
}

DbMetadata/Models/Metadata/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbMetadata.Models.Metadata
{
    public class Department
    {
        public int DepartmentId { get; set; }

        public string Name { get; set; }

        public Organization OwnerOrganization { get; set; }

        public ICollection<DepartmentProperty> Properties { get; set; }

        public ICollection<Project> Projects { get; set; }
    }
}

DbMetadata/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DbMetadata.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DbMetadata.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly MetadataContext _context;

        public DepartmentsController(MetadataContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departments.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d=>d.Properties)
                .Include(d=>d.OwnerOrganization)
                .Include(d=>d.Projects)
                .SingleOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = _context.Organizations
                .Include(o=>o.Departments)
                .SingleOrDefaultAsync(m => m.OrganizationId == id);

            var department = new Department() { OwnerOrganization = organization.Result };
            organization.Result.Departments.Add(department);
            //var property = new DepartmentProperty() { OwnerDepartment = department.Result };
            //organization.Result.Properties.Add(property);
            //_context.Attach(property);
            return View(department);
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                department.OwnerOrganization = _context.Organizations.Find(department.OwnerOrganization.OrganizationId);
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.SingleOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentId,Name")] Department department)
        {
            if (id != department.DepartmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .SingleOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.SingleOrDefaultAsync(m => m.DepartmentId == id);
            _context.Departments.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.DepartmentId == id);
        }
    }
}

DbMetadata/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbMetadata.Models;
using ClosedXML.Excel;
using System.IO;

namespace DbMetadata.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly MetadataContext _context;

        public ProjectsController(MetadataContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var project = await _context.Projects
                .Include(p=>p.OwnerDepartment)
                .Include(p=>p.Properties)
                .Include(p=>p.Documents)
                .Include(p=>p.Tasks)
                .Include(p=>p.Links)
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            foreach(var doc in project.Documents)
            {
                var temp = _context.Documents.Include(m=>m.File).SingleOrDefault(m => m.DocumentId == doc.DocumentId);
                doc.File = temp.File;
            }
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = _context.Departments
                .Include(d =>d.Projects)
                .SingleOrDefaultAsync(m => m.DepartmentId == id);

            var project = new Project() { OwnerDepartment = department.Result };
            department.Result.Projects.Add(project);
            //var property = new DepartmentProperty() { OwnerDepartment = department.Result };
            //organization.Result.Properties.Add(property);
            //_context.Attach(property);
            return View(project);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Project project)
        {
            if (ModelState.IsValid)
            {
                project.OwnerDepartment = _context.Departments.Find(project.OwnerDepartment.DepartmentId);
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,Name")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ProjectId == id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectId == id);
        }

        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(m => m.Properties)
                .Include(m => m.OwnerDepartment.Properties)
                .Include(m => m.OwnerDepartment.OwnerOrganization.Properties)
                .SingleOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            var document = new XLWorkbook(
                Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationBasePath +
                "..\\..\\..\\sample.xlsx");
            var ws = document.Worksheet(1);
            ws.Cell("A1").Value = project.OwnerDepartment.OwnerOrganization.Name;
            ws.Cell("A2").Value = project.OwnerDepartment.Name;
            ws.Cell("A3").Value = project.Name;

            MemoryStream stream = new MemoryStream();
            document.SaveAs(stream);
            stream.Position = 0;

            return File(stream, "application/x-msdownload", project.Name + "_project_card.xlsx");
            //FileStream fileStream = new FileStream(Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationBasePath +
            //    "..\\..\\..\\sample.xlsx", FileMode.Open, FileAccess.Read);
            //byte[] file = new byte[fileStream.Length];
            //fileStream.Read(file, 0, file.Length);
            //return File( file, "application/x-msdownload", project.Name + "_project_card.xlsx");
        }
        //    return File(documentFile.Data, "application/x-msdownload", documentFile.Name);
        //}


        // GET api/Projects/5/GanttData
        [HttpGet]
        [Route("api/Projects/{projectId}/GanttData")]
        public GanttDto GanttData(int projectId)
        {
            return new GanttDto
            {
                data = GetTask(projectId),
                links = GetLink(projectId)
            };
        }

        // GET api/Task
        public IEnumerable<TaskDto> GetTask(int projectId)
        {
            return _context.Tasks
                .Where(t=>t.ProjectId == projectId)
                .ToList()
                .Select(t => (TaskDto)t);
        }


        // GET api/Task/5
        [HttpGet]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public TaskDto GetTask(int projectId,int id)
        {
            return (TaskDto)_context
                .Tasks
                .Find(id);
        }

        // POST api/Task
        [HttpPost]
        [Route("api/Projects/{projectId}/Task")]
        public IActionResult CreateTask(int projectId,TaskDto taskDto)
        {
            var newTask = (DbMetadata.Models.Task)taskDto;

            //save id
            newTask.ProjectId = projectId;

            //save to project
            var project = _context.Projects
                .Include(p => p.Tasks)
                .SingleOrDefaultAsync(m => m.ProjectId == projectId);
            project.Result.Tasks.Add(newTask);

            _context.Tasks.Add(newTask);

            _context.SaveChanges();

            return Ok(new
            {
                tid = newTask.TaskId,
                action = "inserted"
            });
        }

        // DELETE api/Task/5
        [HttpDelete]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public IActionResult DeleteTask(int projectId,int id)
        {
            var task = _context.Tasks.Find(id);
            if (task != null)
            {
                _context.Tasks.Remove(task);
                _context.SaveChanges();
            }

            return Ok(new
            {
                action = "deleted"
            });
        }

        // PUT api/Task/5
        [HttpPut]
        [Route("api/Projects/{projectId}/Task/{id}")]
        public IActionResult EditTask(int projectId, int id, TaskDto taskDto)
        {
            var updatedTask = (DbMetadata.Models.Task)taskDto;
            updatedTask.ProjectId = projectId;
            updatedTask.TaskId = id;
            _context.Entry(updatedTask).State = EntityState.Modified;
            _context.SaveChanges();

            return Ok(new
            {
                action = "updated"
            });
        }

DbMetadata/Views/Departments/Create.cshtml
@model DbMetadata.Models.Department

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerOrganization" class="control-label"></label>
                <input asp-for="OwnerOrganization.OrganizationId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbMetadata/Views/Departments/Delete.cshtml
@model DbMetadata.Models.Department

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DepartmentId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DbMetadata/Views/Departments/Details.cshtml
@model DbMetadata.Models.Department

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OwnerOrganization)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OwnerOrganization.OrganizationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>

<p>
    <a asp-controller="Projects" asp-action="Create" asp-route-id="@Model.DepartmentId">Create New Project</a>
</p>
@{Html.RenderPartial("../Projects/Index", Model.Projects); }

<p>
    <a asp-controller="DepartmentProperties" asp-action="Create" asp-route-id="@Model.DepartmentId">Create New Property</a>
</p>
@{Html.RenderPartial("../DepartmentProperties/Index", Model.Properties); }

<div>
    <a asp-controller="DepartmentProperties" asp-action="Edit" asp-route-id="@Model.DepartmentId">Edit</a> |
    <a asp-controller="DepartmentProperties" asp-action="Index">Back to List</a>
</div>

DbMetadata/Views/Departments/Edit.cshtml
@model DbMetadata.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DepartmentId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbMetadata/Views/Departments/Index.cshtml
@model IEnumerable<DbMetadata.Models.Department>

@{
    ViewData["Title"] = "Index";
}

<h4>Departments</h4>

@*<p>
    <a asp-action="Create">Create New Department</a>
</p>*@
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-controller="Departments" asp-action="Edit" asp-route-id="@item.DepartmentId">Edit</a> |
                <a asp-controller="Departments" asp-action="Details" asp-route-id="@item.DepartmentId">Details</a> |
                <a asp-controller="Departments" asp-action="Delete" asp-route-id="@item.DepartmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>